Add ppx_deriving.runtime to requires in META (#47)
Without this, it is impossible to use `ppx_deriving.runtime` by itself.
For example `utop` would fail with the following error:

```
utop -require ppx_deriving_yojson.runtime
File "_none_", line 1:
Error: Reference to undefined global `Ppx_deriving_runtime'
```